name: Reusable Security Checks

on:
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SAST - SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/bom
          cyclonedx-bom -o bom.xml

